-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0lKjLaWlBDipyqp+
RdrXHXm1ns5M1iI/YJ75DbhphmGgCgYIKoZIzj0DAQehRANCAARxTFHew3l5fjUi
J4QZED/cpl6rmGMpdxLn1n7luIVypzkY5A/u+SHXa5NXhiwmoyDw+Duz3Yqo1tWA
y74O4gP/
-----END PRIVATE KEY-----